[tool.poetry]
name = "nitrain"
version = "0.1.0"
description = "Neuroimaging-native tools for deep learning"
authors = ["ncullen93 <nicholas.cullen@med.lu.se>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"
numpy = "^1.26.4"
nibabel = "^5.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
