on:
  push:
    branches:
      - main

  workflow_dispatch:

name: codecov

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GCP64: ${{ secrets.GCP64 }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5

      - name: Install nitrain-image
        run: python -m pip install git+https://github.com/nitrain/nitrain-image.git

      - name: Install package
        run: python -m pip install .

      - name: Install requirements
        run: python -m pip install -r requirements.txt

      - name: Install other deps
        run: apt-get install git-annex

      - name: Install coverage
        run: python -m pip install coverage

      - name: Unit tests
        run: tests/run_tests.sh -c

      - name: Coveralls
        uses: coverallsapp/github-action@v2.2.3
        with:
          file: tests/coverage.xml
